services:
  db:
    image: postgres:16
    platform: linux/amd64
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .docker-env

  web-prod:
    build:
      context: .
      dockerfile: Dockerfile-prod
    platform: linux/amd64
    volumes:
      - .:/usr/src/app
      - ./data/files:/data/files
    ports:
      - "${WEB_PORT}:8000"
    env_file:
      - .docker-env
    depends_on:
      - db
