[project]
name = "hosp-explorer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "gunicorn>=23.0.0",
    "httpx>=0.27.0",
    "psycopg2>=2.9.11",
    "requests>=2.32.5",
]
